import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { BirdCard } from "../components/bird-card";
import Layout from "../components/layout";
import Button from "../components/button";
import Link from "next/link";

const Home: NextPage = () => {
  const { data: birds } = trpc.bird.getAll.useQuery()

  return (
    <>
      <Head>
        <title>Twitcher</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className="z-auto container mx-auto flex min-h-screen flex-col items-center justify-center px-4 pt-[80px]">
          <section className="pt-6 lg:pt-0">
            <Link href="/new-sighting">
              <Button className="px-6">+ Add New Sighting</Button>
            </Link>
          </section>
          <section className="text-gray-600 ">
            <div className="container px-5 py-12 mx-auto">
              <div className="flex flex-wrap -m-4 justify-center">
                {birds ? (
                  birds.map(bird => (
                    <BirdCard key={bird.id} bird={bird} />
                  ))
                ) : (
                  <p>Loading..</p>
                )}
              </div>
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
};

export default Home;
